version: '3.8'

services:
  nametag3:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        max-time: "5m"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    container_name: nametag3-server
    restart: unless-stopped
